FROM apache/airflow:2.10.3-python3.10

USER root

# ===============================
# Install Java (Spark requirement)
# ===============================
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk curl && \
    apt-get clean

# ===============================
# Install Spark client
# ===============================
ENV SPARK_VERSION=3.5.1
ENV HADOOP_VERSION=3

RUN curl -L https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz \
    | tar -xz -C /opt/ && \
    mv /opt/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} /opt/spark

ENV SPARK_HOME=/opt/spark
ENV SPARK_CONF_DIR=/opt/spark/conf
ENV PATH=/opt/spark/bin:/opt/spark/sbin:$PATH

USER airflow